name: CI/CD

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test_devportal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true
      - run: bundle exec jekyll build
      - run: bundle exec rake test_ci
      - uses: actions/upload-artifact@v3
        with:
          name: _devportal
          retention-days: 7
          path: |
            _site/
            firebase.json

  build_test_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ePages-de/epages-docs
          ref: master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true
      - run: bundle exec jekyll build
      - run: bundle exec rake test_ci
      - uses: actions/upload-artifact@v3
        with:
          name: _docs
          retention-days: 7
          path: |
            _site/

  combine_projets:
    runs-on: ubuntu-latest
    needs:
      - build_test_devportal
      - build_test_docs
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: _devportal
      - uses: actions/download-artifact@v3
        with:
          name: _docs
          path: ./_docs
      - run: rsync -abviuzP _docs/ _site/
      - uses: actions/upload-artifact@v3
        with:
          name: _site
          retention-days: 7
          path: |
            _site/
            firebase.json

  deploy_staging:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    needs:
      - combine_projets
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: _site
      - run: ls -lash
      - run: ls -lash _site
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install --save-dev firebase-tools
      - run: firebase deploy --project $FIREBASE_PROJECT --token=$FIREBASE_TOKEN --non-interactive
        env:
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_APP_NAME_STAGING }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy_production:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs:
      - combine_projets
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: _site
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install --save-dev firebase-tools
      - run: firebase deploy --project $FIREBASE_PROJECT --token=$FIREBASE_TOKEN --non-interactive
        env:
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_APP_NAME_PRODUCTION }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  # deploy_production:
  #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
  #   needs:
  #     - build_test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ePages-de/action-deploy-heroku@master
  #       with:
  #         heroku_api_key: ${{ secrets.T42_HEROKU_API_KEY }}
  #         heroku_app_name: ${{ secrets.HEROKU_APP_NAME_PRODUCTION }}
  #         heroku_email: ${{ secrets.T42_HEROKU_EMAIL }}
  #         heroku_branch: master
  #         heroku_team: ${{ secrets.T42_HEROKU_TEAM }}
  #         mattermost_webhook_url: ${{ secrets.T42_MATTERMOST_NOTIFICATION_WEBHOOK }}
  #         mattermost_username: beyond_admin
  #         github_job: ${{ github.job }}
  #         github_workflow: ${{ github.workflow }}
  #         github_repository: ${{ github.repository }}
  #         github_run_id: ${{ github.run_id }}
