name: CI/CD

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test_devportal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  # deploy_production:
  #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
  #   needs:
  #     - build_test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ePages-de/action-deploy-heroku@master
  #       with:
  #         heroku_api_key: ${{ secrets.T42_HEROKU_API_KEY }}
  #         heroku_app_name: ${{ secrets.HEROKU_APP_NAME_PRODUCTION }}
  #         heroku_email: ${{ secrets.T42_HEROKU_EMAIL }}
  #         heroku_branch: master
  #         heroku_team: ${{ secrets.T42_HEROKU_TEAM }}
  #         mattermost_webhook_url: ${{ secrets.T42_MATTERMOST_NOTIFICATION_WEBHOOK }}
  #         mattermost_username: beyond_admin
  #         github_job: ${{ github.job }}
  #         github_workflow: ${{ github.workflow }}
  #         github_repository: ${{ github.repository }}
  #         github_run_id: ${{ github.run_id }}
